import { FilterSearch } from "@/components/filter-search";
import { LayoutHome } from "@/components/layouts";
import { Footer } from "@/components/layouts/footer";
import { HeaderMenuSearch, HeaderSearchV2 } from "@/components/layouts/headers";
import HeaderBack from "@/components/layouts/headers/HeaderBack";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Footer />
    </>
  );
};

// Home.Layout = LayoutHome;

export default Home;
