import { ResultSearch } from "@/components/result-search";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-5">
        <ResultSearch />
      </div>
    </>
  );
};

// Home.Layout = LayoutHome;

export default Home;
